### ISSUE TITLE
Missing TypeScript implementation

### ISSUE THREAD

**Issue by Visualizememe** [mawerty/Is-Prime#1]
Dear maintainer,

I was redirected here by a Reddit post, and I have been looking for a project like this for ages (finally found it!). From the tests it really seems like a stable implementation with high accuracy of the corresponding results.

 I see that you have a normal JavaScript implementation, however due to internal, strict requirements, I need this in TypeScript. 

Any chance you would be able to implement this awesome library in typescript and publish it to NPM? Thanks in advance!

Sincerely,
Martin.

**Comment by mawerty** [comment]
Fixed!
When I will have some free time, I will create a library and push it into NPM.
