### ISSUE TITLE
Add contribution guidelines

### ISSUE THREAD

**Issue by PalmDevs** [mawerty/Is-Prime#33]
It should tell what naming convention to use and where. So far, I've seen parameter names being inconsistent as well as the parent class names (for OO languages).

I'd suggest making contributors use the language's casing style for method/function names. Eg. for JS use camelCase and for Python use snake_case.

**Comment by mawerty** [comment]
I have updated README file. Now it is okay, did I forget something/did something wrong?

**Comment by Acters** [comment]
Making the function take the smallest amount of space/data in memory will be the most optimized approach.

**Comment by Acters** [comment]
To clarify someone asked something like this in StackOverflow https://stackoverflow.com/questions/21757755/what-in-the-function-is-occupying-memory-space

**Comment by mawerty** [comment]
The most optimized approach is one that works, and takes least space.

**Comment by Acters** [comment]
Guidelines should demand that the assembly output of a compiled language should match the assembly code in the repository.

**Comment by mawerty** [comment]
Yeah, but then the code would be too complicated and not that fun.

**Comment by Acters** [comment]
I thought the idea of this was to create an O(1) time complexity that translates to 1 instruction cycle of the CPU. How do all different languages compare to the true assembly approach of XOR eax, eax? Are we truly reaching O(1) time complexity if the code is not fine tuned to match the desired Assembly output?

**Comment by mawerty** [comment]
O(1) means that regardless of the number we ask for, the execution time of our program will be constant and always the same

**Comment by PalmDevs** [comment]
The current one looks okay to me. Closing this
