### ISSUE TITLE
Optimised main.txt is 1 byte larger than normal one

### ISSUE THREAD

**Issue by EonTAS** [mawerty/Is-Prime#59]
normal optimisation is 2 bytes large
![image](https://user-images.githubusercontent.com/16490469/230800164-c39d32b9-7bc8-4c88-9ab8-b7a99d883723.png)
optimised is 3 bytes large
![image](https://user-images.githubusercontent.com/16490469/230800173-34a4f2f8-162c-4187-b581-29b49ce70cc4.png)

i dont think you can call that optimised

**Comment by mawerty** [comment]
Fixed!
