### ISSUE TITLE
SQL ?????

### ISSUE THREAD

**Issue by teub** [mawerty/Is-Prime#60]
Do you think there could be a SQL implementation ?
Would you recommend storing "false" in its own table so it can be shared and thus optimize the memory footprint ?

**Comment by mawerty** [comment]
If you can implement and PR it then sure

**Comment by teub** [comment]
sorry I don't know SQL

**Comment by mawerty** [comment]
I have never wrotten a single line of SQL in my life but its sounds like great idea

**Comment by mawerty** [comment]
Idk maybe someone will do it soon

**Comment by teub** [comment]
maybe there needs to be a code bounty because SQL sounds very useful

**Comment by PalmDevs** [comment]
Here you go
```sql
DROP *
```
Please make sure to test this on a database with a lot of important data.

**Comment by Acters** [comment]
SQL is a server that handles databases. Most programs return false. for an Is_Prime function call. This would essentially be:

SELECT false;

This will return the table name as false, and one database value of 0.
